namespace applanch.Theming;

public enum ThemeBrushKey
{
    AppBackground,
    Surface,
    SurfaceBorder,
    TextPrimary,
    SidebarPinSlash,
    TextSecondary,
    TextTertiary,
    ScrollbarThumb,
    PrereleaseBadgeBackground,
    PrereleaseBadgeBorder,
    PrereleaseBadgeText,
    ItemBackground,
    ItemBorder,
    IconBackground,
    NotificationInfoBackground,
    NotificationInfoBorder,
    NotificationActionHover,
    NotificationWarningBackground,
    NotificationWarningBorder,
    MissingPathWarningBadge,
    NotificationErrorBackground,
    NotificationErrorBorder,
    NotificationProgressTrack,
    NotificationProgressValue,
    QuickAddInfoText,
    QuickAddWarningText,
    DialogInfo,
    DialogQuestion,
    DialogWarning,
    DialogError,
}