// <auto-generated>
//     This file provides strongly-typed access to the localized string resources
//     in Properties/Resources.resx and its satellite assemblies.
//     Resource lookup is performed against Thread.CurrentThread.CurrentUICulture.
// </auto-generated>

using System.Globalization;
using System.Resources;

namespace applanch.Properties;

#nullable enable

public static class Resources
{
    private static ResourceManager? s_resourceManager;

    private static ResourceManager ResourceMgr =>
        s_resourceManager ??= new ResourceManager("applanch.Properties.Resources", typeof(Resources).Assembly);

    private static string Get(string name) =>
        ResourceMgr.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    // ── Main window ──────────────────────────────────────────────────────────

    public static string Subtitle                => Get(nameof(Subtitle));
    public static string ToolTip_Update          => Get(nameof(ToolTip_Update));
    public static string ToolTip_Settings        => Get(nameof(ToolTip_Settings));
    public static string Banner_UpdateButton     => Get(nameof(Banner_UpdateButton));
    public static string SectionLabel_Category   => Get(nameof(SectionLabel_Category));
    public static string Expander_AddApp         => Get(nameof(Expander_AddApp));
    public static string ToolTip_NameOrPath      => Get(nameof(ToolTip_NameOrPath));
    public static string ToolTip_Category        => Get(nameof(ToolTip_Category));
    public static string ToolTip_Arguments       => Get(nameof(ToolTip_Arguments));
    public static string Button_Add              => Get(nameof(Button_Add));
    public static string Hint_AddApp             => Get(nameof(Hint_AddApp));
    public static string Menu_Rename             => Get(nameof(Menu_Rename));
    public static string Menu_ChangeCategory     => Get(nameof(Menu_ChangeCategory));
    public static string Menu_ChangeArguments    => Get(nameof(Menu_ChangeArguments));
    public static string Menu_Delete             => Get(nameof(Menu_Delete));
    public static string ToolTip_DragToReorder   => Get(nameof(ToolTip_DragToReorder));
    public static string ToolTip_Delete          => Get(nameof(ToolTip_Delete));
    public static string EmptyMessage            => Get(nameof(EmptyMessage));

    // ── Settings window ──────────────────────────────────────────────────────

    public static string Window_Settings              => Get(nameof(Window_Settings));
    public static string Section_Appearance           => Get(nameof(Section_Appearance));
    public static string Setting_Theme                => Get(nameof(Setting_Theme));
    public static string Theme_System                 => Get(nameof(Theme_System));
    public static string Theme_Light                  => Get(nameof(Theme_Light));
    public static string Theme_Dark                   => Get(nameof(Theme_Dark));
    public static string Section_Behavior             => Get(nameof(Section_Behavior));
    public static string Setting_CloseOnLaunch        => Get(nameof(Setting_CloseOnLaunch));
    public static string Setting_CloseOnLaunchDesc    => Get(nameof(Setting_CloseOnLaunchDesc));
    public static string Setting_CheckForUpdates      => Get(nameof(Setting_CheckForUpdates));
    public static string Setting_CheckForUpdatesDesc  => Get(nameof(Setting_CheckForUpdatesDesc));
    public static string Section_Debug                => Get(nameof(Section_Debug));
    public static string Setting_DebugUpdate          => Get(nameof(Setting_DebugUpdate));
    public static string Setting_DebugUpdateDesc      => Get(nameof(Setting_DebugUpdateDesc));

    // ── Prompt dialog ────────────────────────────────────────────────────────

    public static string Button_Cancel           => Get(nameof(Button_Cancel));
    public static string Prompt_ChangeCategory   => Get(nameof(Prompt_ChangeCategory));
    public static string Prompt_ChangeArguments  => Get(nameof(Prompt_ChangeArguments));

    // ── Messages (use string.Format with these) ──────────────────────────────

    /// <summary>Format: v{0} = new version, v{1} = current version</summary>
    public static string UpdateMessage                  => Get(nameof(UpdateMessage));
    /// <summary>Format: {0} = exception message</summary>
    public static string UpdateFailed                   => Get(nameof(UpdateFailed));
    /// <summary>Format: {0} = path</summary>
    public static string Error_FileNotFound             => Get(nameof(Error_FileNotFound));
    public static string Error_LaunchFailed             => Get(nameof(Error_LaunchFailed));
    /// <summary>Format: {0} = exception message</summary>
    public static string Error_LaunchFailedWithMessage  => Get(nameof(Error_LaunchFailedWithMessage));
    public static string AllCategories                  => Get(nameof(AllCategories));
    public static string DefaultCategory                => Get(nameof(DefaultCategory));
    public static string Error_QuickAddEmpty            => Get(nameof(Error_QuickAddEmpty));
    /// <summary>Format: {0} = user input</summary>
    public static string Error_QuickAddNotFound         => Get(nameof(Error_QuickAddNotFound));
    public static string Error_AlreadyRegistered        => Get(nameof(Error_AlreadyRegistered));
    public static string ContextMenu_Register           => Get(nameof(ContextMenu_Register));
}
