using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace applanch.ResourceGenerator;

internal static class ResourcesCodeBuilder
{
    public static string Build(string rootNamespace, ImmutableArray<ResourceEntry> entries)
    {
        var classBuilder = new StringBuilder();
        var usedIdentifiers = new Dictionary<string, int>(System.StringComparer.Ordinal);

        foreach (var entry in entries)
        {
            var identifier = IdentifierSanitizer.Sanitize(entry.Name);
            if (usedIdentifiers.TryGetValue(identifier, out var count))
            {
                count++;
                usedIdentifiers[identifier] = count;
                identifier = identifier + "_" + count;
            }
            else
            {
                usedIdentifiers[identifier] = 1;
            }

            classBuilder.Append("    public static string ")
                        .Append(identifier)
                        .Append(" => Get(\"")
                        .Append(Escape(entry.Name))
                        .AppendLine("\");");
        }

        var sourceBuilder = new StringBuilder();
        sourceBuilder.AppendLine("// <auto-generated />");
        sourceBuilder.AppendLine("using System.Globalization;");
        sourceBuilder.AppendLine("using System.Resources;");
        sourceBuilder.AppendLine();
        sourceBuilder.Append("namespace ")
            .Append(rootNamespace)
            .AppendLine(".Properties;");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("#nullable enable");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("public static class Resources");
        sourceBuilder.AppendLine("{");
        sourceBuilder.AppendLine("    private static ResourceManager? s_resourceManager;");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("    private static ResourceManager ResourceMgr =>");
        sourceBuilder.Append("        s_resourceManager ??= new ResourceManager(\"")
            .Append(rootNamespace)
            .AppendLine(".Properties.Resources\", typeof(Resources).Assembly);");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("    private static string Get(string name) =>");
        sourceBuilder.AppendLine("        ResourceMgr.GetString(name, CultureInfo.CurrentUICulture) ?? name;");
        sourceBuilder.AppendLine();
        sourceBuilder.Append(classBuilder);
        sourceBuilder.AppendLine("}");

        return sourceBuilder.ToString();
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
